### ISSUE TITLE
[CRITICAL] WORKER TIMEOUT ?

### ISSUE THREAD

**Issue by Tharic99** [mikenye/docker-striparr#1] opened 2019-11-12 15:02 UTC
I'm seeing this error pretty much all the time lately for some reason. Restarted the container, deleted it and pulled it down again, same thing.

```
[listener] [2019-11-11 03:17:08,121: INFO] [172.18.0.1] [Sonarr/2.0.0.5338 (ubuntu 18.04)] Enqueuing processing of file: "/tv/tv-shows/Silicon Valley/Season 06/showname1.mkv",
[worker] [2019-11-11 03:17:31,177: INFO/ForkPoolWorker-1] striparr.worker[30d6c92c-5827-484f-b705-30720abd248e]: Checking: "/tv/tv-shows/Silicon Valley/showname1.mkv",
[worker] [2019-11-11 03:17:40,844: INFO/ForkPoolWorker-1] striparr.worker[30d6c92c-5827-484f-b705-30720abd248e]: File already clean: "/tv/tv-shows/showname1.mkv",
[listener] [2019-11-11 10:13:43,348: INFO] [172.18.0.1] [Sonarr/2.0.0.5338 (ubuntu 18.04)] Enqueuing processing of file: "/tv/tv-shows/showname2.mkv",
[listener] [2019-11-11 10:13:56 +0000] [220] [CRITICAL] WORKER TIMEOUT (pid:476),
[listener] [2019-11-11 10:14:03 +0000] [487] [INFO] Booting worker with pid: 487,
[listener] [2019-11-11 16:10:44,683: INFO] [172.18.0.1] [Radarr/0.2.0.1358 (Linux 4.15)] Enqueuing processing of file: "/movies/moviename.mp4",
[listener] [2019-11-11 16:11:06 +0000] [220] [CRITICAL] WORKER TIMEOUT (pid:487),
[listener] [2019-11-11 16:11:10 +0000] [494] [INFO] Booting worker with pid: 494,
```
Any ideas?

**Comment by mikenye** [comment] 2019-11-14 09:23
Hi @Tharic99,

I'm currently looking into this issue. It looks like it may be related to this issue: https://github.com/benoitc/gunicorn/issues/1801

Could you tell me about the environment where you're running striparr? I haven't had this issue  personally and am wondering if it could be related to a slower system and/or slower disk where I may need to increase the worker timeout...

Thanks.

-Mike

**Comment by mikenye** [comment] 2019-11-14 10:08
OK. I've just increased the worker timeout from the default of 30 seconds up to 10 minutes to prevent workers from timing out when running on "slower" hardware.

Can I please ask you to:
- Pull `mikenye/striparr:fix_issue_1` (note the different tag, this is a troubleshooting release just for you)
- Re-create your container using `mikenye/striparr:fix_issue_1`
- Keep an eye on the container logs and see if the problem is resolved.

Thanks.

-Mike

**Comment by Tharic99** [comment] 2019-11-19 14:47
Mike,

Just wanted to follow-up with you. I've been running the updated container (THANK YOU!) since the 14th now and it's pulled in a dozen or so different things and I haven't seen the error a single time. It seems like the worker timeout resolved the issue!

**Comment by mikenye** [comment] 2019-11-20 02:16
Hi @Tharic99, that's great news! I'll roll the changes into the master branch and will push an updated "latest" version of the image. I'll leave this issue open until that time, and update you when it's available. Thanks so much for reporting the issue so we can make this image better for everyone. 👍

**Comment by mikenye** [comment] 2019-11-20 02:42
Hi @Tharic99, the new `latest` version of the image is now available. You'll need to:

 - Pull `mikenye/striparr:latest`
 - Re-create your container using `mikenye/striparr:latest`

I've removed the `fix_issue_1` version of the image, so I'd encourage you to switch over to the new `latest`.

Thanks again. I'll now close this issue out.

**Closed by mikenye** 2019-11-20 02:42 UTC
Labels: resolved
